name: Bug report
description: Create a bug report to help us address errors in the repository
title: '[BUG] <bug description>'
labels: [bug]
body:
  - type: textarea
    id: bugdescription
    attributes:
      label: Description of the bug
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Please add screenshots (if applicable)
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Add any other context about the problem here
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/WebXDAO/start-here/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
